version: '3'
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./Data:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4j
  nodeApp:
    image: node:10
    depends_on: neo4j
    ports:
      - 80:3000
    volumes:
      - ./home/node/app:/app
    environment:
      - PORT=3000
      - NEO4JSERVER=neo4j
      - USERDB=neo4j
      - PASSDB=neo4j
    command:
      - node app.js
networks:
  default:
    external:
      name: resApp